// Use case for creating users
const { ValidationError } = require('../../../shared/errors');

class CreateUserUseCase {
  constructor(userRepository) {
    this.userRepository = userRepository;
  }
  
  async execute(userData) {
    // Input validations
    if (!userData.firstName) {
      throw new ValidationError('First name is required');
    }
    
    if (!userData.lastName) {
      throw new ValidationError('Last name is required');
    }
    
    if (!userData.email) {
      throw new ValidationError('Email is required');
    }
    
    if (!userData.roles || userData.roles.length === 0) {
      throw new ValidationError('At least one role is required');
    }
    
    // Check if email already exists
    const existingUser = await this.userRepository.findByEmail(userData.email);
    if (existingUser) {
      throw new ValidationError('Email already exists');
    }
    
    // Create the entity
    const User = require('../../domain/entities/User');
    
    const user = new User(
      null, // ID will be generated by repository
      userData.firstName,
      userData.lastName,
      new Date(),
      'active',
      userData.roles
    );
    
    // Save using repository
    const savedUser = await this.userRepository.save(user);
    
    return savedUser;
  }
}

module.exports = CreateUserUseCase;
